// Generated by CoffeeScript 1.7.1
(function() {
  describe('Index', function() {
    var categ, index, tangle;
    categ = index = tangle = null;
    beforeEach(function() {
      categ = new Category('ml/tf', 60, 'osc');
      index = new Indicator('fatf', 50, categ);
      tangle = {
        setValue: function(variable, value) {},
        getValue: function(variable) {
          return 55;
        }
      };
      return Index.set_tangle(tangle);
    });
    describe('set_weight', function() {
      beforeEach(function() {
        spyOn(tangle, 'setValue');
        return index.set_weight(23);
      });
      it('sets the weight attribute', function() {
        return expect(index.weight).toEqual(23.);
      });
      return it('sets the value via the tangle', function() {
        return expect(tangle.setValue).toHaveBeenCalled();
      });
    });
    return describe('get_weight', function() {
      it('returns the value via the tangle', function() {
        spyOn(tangle, 'getValue');
        index.get_weight();
        return expect(tangle.getValue).toHaveBeenCalledWith(index.variable);
      });
      return it('returns the correct value', function() {
        return expect(index.get_weight()).toEqual(55);
      });
    });
  });

}).call(this);
